# Configuration for flavours
# https://github.com/Misterio77/flavours

[[items]]
file = "~/.emacs.d/base16-generated-theme.el"
template = "emacs"
rewrite = true

[[items]]
file = "~/.config/kitty/theme.conf"
template = "kitty"
rewrite = true

[[items]]
file = "~/.config/mako/config"
template = "mako"
rewrite = true

[[items]]
file = "~/.local/share/konsole/base16-generated.colorscheme"
template = "konsole"
rewrite = true

[[items]]
file = "~/.config/waybar/style.css"
template = "waybar"
start = "/* Start flavours */"
end = "/* End flavours */"

[[items]]
file = "~/.config/alacritty/flavours.toml"
template = "alacritty"
rewrite = true
